#!/bin/sh

while true
do
	printf "input_file: "
	read INPUT_FILE
	INPUT_FILE=$(printf "%s" "$INPUT_FILE" | sed "s#~#$HOME#")
	test -f "$INPUT_FILE" && break
	echo "Such file '$INPUT_FILE' does not exist, try again"
done

while true
do
	printf "keyfile: "
	stty -echo
	read KEYFILE
	stty echo
	KEYFILE=$(printf "%s" "$KEYFILE" | sed "s#~#$HOME#")
	test -f "$KEYFILE" && break
	echo "Such file does not exist, try again"
done

printf "pass: "
stty -echo
read PASS
stty echo

PLAIN=$(printf \
	"%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n" \
	"decrypt" \
	"$PASS" \
	"$KEYFILE" \
	"$INPUT_FILE" \
	"-" \
	| tmenc-cli )

while true
do
	printf "query: "
	read QUERY
	test -n "$QUERY" || break
	printf "%s" "$PLAIN" | grep --color=yes -i -B 3 -A 20 -e $QUERY
done

