#!/bin/sh

# NOTE: reasonable defaults
INPUT_WRAP_COUNT=256
WRAP_COUNT=0

while true
do
	case "$1" in
		--input-wrap-count=*)
			INPUT_WRAP_COUNT=$(echo "$1" | sed 's/.*=//')
			;;
		--wrap-count=*)
			WRAP_COUNT=$(echo "$1" | sed 's/.*=//')
			;;
		*)
			break
			;;
	esac
	shift
done

while true
do
	printf "input_file: " 1>&2
	read INPUT_FILE
	INPUT_FILE=$(printf "%s" "$INPUT_FILE" | sed "s#~#$HOME#")
	test -f "$INPUT_FILE" && break
	echo "Such file does not exist, try again" 1>&2
done

while true
do
	printf "keyfile: " 1>&2
	stty -echo
	read KEYFILE
	stty echo
	KEYFILE=$(printf "%s" "$KEYFILE" | sed "s#~#$HOME#")
	test -f "$KEYFILE" && break
	echo "Such file does not exist, try again" 1>&2
done

printf "pass: " 1>&2
stty -echo
read PASS
stty echo

SALT=$(cat /dev/urandom | basenc --base16 --wrap 0 | head -c 256) # 1024-bit random salt

printf "output_file: " 1>&2
read OUTPUT_FILE
OUTPUT_FILE=$(printf "%s" "$OUTPUT_FILE" | sed "s#~#$HOME#")

echo "Encrypting with:"
echo "   INPUT_WRAP_COUNT=$INPUT_WRAP_COUNT"
echo "   WRAP_COUNT=$WRAP_COUNT"
echo "   SALT=$SALT"

printf \
	"%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n" \
	"encrypt" \
	"$PASS" \
	"$SALT" \
	"$KEYFILE" \
	"$INPUT_WRAP_COUNT" \
	"$WRAP_COUNT" \
	"$INPUT_FILE" \
	"$OUTPUT_FILE" \
	 | tmenc-cli


