#!/bin/sh

while true
do
	printf "input_file: " 1>&2
	read INPUT_FILE
	INPUT_FILE=$(printf "%s" "$INPUT_FILE" | sed "s#~#$HOME#")
	test -f "$INPUT_FILE" && break
	echo "Such file '$INPUT_FILE' does not exist, try again" 1>&2
done

while true
do
	printf "keyfile: " 1>&2
	stty -echo
	read KEYFILE
	stty echo
	KEYFILE=$(printf "%s" "$KEYFILE" | sed "s#~#$HOME#")
	test -f "$KEYFILE" && break
	echo "Such file does not exist, try again" 1>&2
done

printf "pass: " 1>&2
stty -echo
read PASS
stty echo

printf \
	"%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n" \
	"decrypt" \
	"$PASS" \
	"$KEYFILE" \
	"$INPUT_FILE" \
	"-" \
	| tmenc-cli \
	| vim -n -

