#! /bin/sh

CURRENT_TTY=$(tty)

TEMPNAME=$(cat /dev/urandom | base32 | head -c 20)
mkfifo "$TEMPNAME"

while true
do
	printf "input_file: " 1>&2
	read INPUT_FILE
	INPUT_FILE=$(printf "%s" "$INPUT_FILE" | sed "s#~#$HOME#")
	test -f "$INPUT_FILE" && break
	echo "Such file '$INPUT_FILE' does not exist, try again" 1>&2
done

while true
do
	printf "keyfile: " 1>&2
	stty -echo
	read KEYFILE
	stty echo
	echo

	KEYFILE=$(printf "%s" "$KEYFILE" | sed "s#~#$HOME#")
	test -z "$KEYFILE" && break
	test -f "$KEYFILE" && break
	echo "Such file does not exist, try again" 1>&2
done

printf "pass: " 1>&2
stty -echo
read PASS
stty echo
echo

printf \
	"%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n" \
	"decrypt" \
	"$PASS" \
	"$KEYFILE" \
	"$INPUT_FILE" \
	"$TEMPNAME" \
	| tmenc-cli &

( cat "$TEMPNAME" | vim -n - ) &
PID1=$?

sleep 1
rm -f "$TEMPNAME"

sleep 300

( cat /dev/urandom | base32 --wrap=0 > "$CURRENT_TTY" ) &
PID2=$?
( cat /dev/urandom | base32 --wrap=0 ) &
PID3=$?
sleep 10

kill -2 "$PID1"
sleep 1
kill -15 "$PID1"
sleep 1
kill -1 "$PID1"
sleep 1
kill -9 "$PID1"
sleep 1

kill -1 "$PID2"
kill -1 "$PID3"

