#!/bin/sh

printf "pass: "
read PASS

# printf "salt: "
# read SALT
SALT=$(cat /dev/urandom | basenc --base16 | head -c 256) # 1024-bit random salt

printf "keyfile: "
read KEYFILE

# printf "input_wrap_count: "
# read INPUT_WRAP_COUNT
INPUT_WRAP_COUNT=1000

# printf "wrap_count: "
# read WRAP_COUNT
WRAP_COUNT=0

printf "input_file: "
read INPUT_FILE

printf "output_file: "
read OUTPUT_FILE

printf \
	"%s%s\n%s\n%s\n%s\n%s\n%s\n%s\n" \
	"encrypt" \
	"$PASS" \
	"$SALT" \
	"$KEYFILE" \
	"$INPUT_WRAP_COUNT" \
	"$WRAP_COUNT" \
	"$INPUT_FILE" \
	"$OUTPUT_FILE" \
	 | tmenc-cli


