#!/bin/sh

while true
do
	printf "input_file: "
	read INPUT_FILE
	INPUT_FILE=$(printf "%s" "$INPUT_FILE" | sed "s#~#$HOME#")
	test -f "$INPUT_FILE" && break
	echo "Such file does not exist, try again"
done

while true
do
	printf "keyfile: "
	stty -echo
	read KEYFILE
	stty echo
	KEYFILE=$(printf "%s" "$KEYFILE" | sed "s#~#$HOME#")
	test -f "$KEYFILE" && break
	echo "Such file does not exist, try again"
done

printf "pass: "
stty -echo
read PASS
stty echo

# printf "salt: "
# read SALT
SALT=$(cat /dev/urandom | basenc --base16 | head -c 256) # 1024-bit random salt

INPUT_WRAP_COUNT=1000
WRAP_COUNT=0

printf "output_file: "
read OUTPUT_FILE
OUTPUT_FILE=$(printf "%s" "$OUTPUT_FILE" | sed "s#~#$HOME#")

printf \
	"%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n" \
	"encrypt" \
	"$PASS" \
	"$SALT" \
	"$KEYFILE" \
	"$INPUT_WRAP_COUNT" \
	"$WRAP_COUNT" \
	"$INPUT_FILE" \
	"$OUTPUT_FILE" \
	 | tmenc-cli


